config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :expertises
  resources :skills
  resources :experts
  resources :todos
  resources :questions
  post '/question_form', to: 'experts#load_expert_form'
  get '/question_form', to: 'experts#submit_question'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/search', to: 'questions#search'
  post '/submit_question', to: 'experts#submit_question'
  post '/find_expertises', to: 'experts#find_expertises'
  get '/update_expertises', to: 'experts#load_expert_lookup'
  root 'home#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/expertises_controller.rb
class ExpertisesController < ApplicationController
  before_action :set_expertise, only: [:show, :edit, :update, :destroy]

  # GET /expertises
  # GET /expertises.json
  def index
    @expertises = Expertise.all
  end

  # GET /expertises/1
  # GET /expertises/1.json
  def show
  end

  # GET /expertises/new
  def new
    @expertise = Expertise.new
  end

  # GET /expertises/1/edit
  def edit
  end

  # POST /expertises
  # POST /expertises.json
  def create
    @expertise = Expertise.new(expertise_params)

    respond_to do |format|
      if @expertise.save
        format.html { redirect_to @expertise, notice: 'Expertise was successfully created.' }
        format.json { render :show, status: :created, location: @expertise }
      else
        format.html { render :new }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expertises/1
  # PATCH/PUT /expertises/1.json
  def update
    respond_to do |format|
      if @expertise.update(expertise_params)
        format.html { redirect_to @expertise, notice: 'Expertise was successfully updated.' }
        format.json { render :show, status: :ok, location: @expertise }
      else
        format.html { render :edit }
        format.json { render json: @expertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expertises/1
  # DELETE /expertises/1.json
  def destroy
    @expertise.destroy
    respond_to do |format|
      format.html { redirect_to expertises_url, notice: 'Expertise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expertise
      @expertise = Expertise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expertise_params
      params.require(:expertise).permit(:skill_id, :expert_id, :level)
    end
end

app/helpers/expertises_helper.rb
module ExpertisesHelper
  require "pry"
  def LoadData
    binding.pry
  end
end

app/views/expertises/_form.html.erb
<%= form_with(model: expertise, local: true) do |form| %>
  <% if expertise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expertise.errors.count, "error") %> prohibited this expertise from being saved:</h2>

      <ul>
      <% expertise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :skill_id %>
    <%= form.text_field :skill_id, id: :expertise_skill_id %>
  </div>

  <div class="field">
    <%= form.label :expert_id %>
    <%= form.text_field :expert_id, id: :expertise_expert_id %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level, id: :expertise_level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expertises/edit.html.erb
<h1>Editing Expertise</h1>

<%= render 'form', expertise: @expertise %>

<%= link_to 'Show', @expertise %> |
<%= link_to 'Back', expertises_path %>

app/views/expertises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expertises</h1>

<table>
  <thead>
    <tr>
      <th>Expert</th>
      <th>Expert Email</th>
      <th>Skill</th>
      <th>Level</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @expertises.each do |expertise| %>
      <tr>
        <td><%= image_tag expertise.expert.picture_url %></td>
        <td><%= expertise.expert.name %></td>
        <td><%= expertise.expert.email %></td>
        <td><%= expertise.skill.name %></td>
        <td><%= expertise.level %></td>
        <td><%= link_to 'Show', expertise %></td>
        <td><%= link_to 'Edit', edit_expertise_path(expertise) %></td>
        <td><%= link_to 'Destroy', expertise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expertise', new_expertise_path %>

app/views/expertises/new.html.erb
<h1>New Expertise</h1>

<%= render 'form', expertise: @expertise %>

<%= link_to 'Back', expertises_path %>

app/views/expertises/no_viable_experts.html.erb
<h1>There are no experts in that skill :( </h1>

app/views/expertises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expert Name:</strong>
  <%= @expertise.expert.name %>
</p>
<p>
  <strong>Expert Email:</strong>
  <%= @expertise.expert.email %>
</p>

<p>
  <strong>Level:</strong>
  <%= @expertise.level %>
</p>
<p>
  <strong>Skill:</strong>
  <%= @expertise.skill.name %>
</p>


<%= link_to 'Edit', edit_expertise_path(@expertise) %> |
<%= link_to 'Back', expertises_path %>

app/views/expertises/viable_experts.html.erb
<p id="notice"><%= notice %></p>
<h1>Here are the experts in <%= @expertises.first.skill.name %> </h1>
<table class = "table table-striped table-bordered">
  <thead>
    <tr>
      <th>Picture </th>
      <th>Expert Name</th>
      <th>Expert Email</th>
      <th>Job Title</th>
      <th>Skill Level</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @expertises.each do |expertise| %>
      <tr>
        <td><%= image_tag expertise.expert.picture_url %></td>
        <td><%= expertise.expert.name %></td>
        <td><%= expertise.expert.email %></td>
        <td><%= expertise.expert.job_title %></td>
        <td><%= expertise.level %></td>
        <td><%= button_to("Ask A Question", {:controller => "experts", :action => "load_expert_form", :expertise_id => expertise.id})%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>