config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :expertises
  resources :skills
  resources :experts
  resources :todos
  resources :questions
  post '/question_form', to: 'experts#load_expert_form'
  get '/question_form', to: 'experts#submit_question'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/search', to: 'questions#search'
  post '/submit_question', to: 'experts#submit_question'
  post '/find_expertises', to: 'experts#find_expertises'
  get '/update_expertises', to: 'experts#load_expert_lookup'
  root 'home#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/expert.rb
class Expert < ApplicationRecord
  has_many :expertises
  def self.from_omniauth(auth)
  where(email: auth.info.email).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.email = auth.info.email
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end
end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  before_action :set_expert, only: [:show, :edit, :update, :destroy]

  # GET /experts
  # GET /experts.json
  def index
    @experts = Expert.all
  end
  def load_expert_lookup
    render "experts/look_up_expert"
  end
  # GET /experts/1
  # GET /experts/1.json
  def show
  end
  def find_expertises
    binding.pry
  end
  def load_expert_form
    expertise_id = params[:expertise_id]
    @expertise = Expertise.find_by_id(expertise_id)
    render "experts/ask_expert"
  end
  def submit_question
    @question = params[:question]
    render "questions/success"
  end
  # GET /experts/new
  def new
    @expert = Expert.new
  end

  # GET /experts/1/edit
  def edit
  end

  # POST /experts
  # POST /experts.json
  def create
    @expert = Expert.new(expert_params)

    respond_to do |format|
      if @expert.save
        format.html { redirect_to @expert, notice: 'Expert was successfully created.' }
        format.json { render :show, status: :created, location: @expert }
      else
        format.html { render :new }
        format.json { render json: @expert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experts/1
  # PATCH/PUT /experts/1.json
  def update
    respond_to do |format|
      if @expert.update(expert_params)
        format.html { redirect_to @expert, notice: 'Expert was successfully updated.' }
        format.json { render :show, status: :ok, location: @expert }
      else
        format.html { render :edit }
        format.json { render json: @expert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experts/1
  # DELETE /experts/1.json
  def destroy
    @expert.destroy
    respond_to do |format|
      format.html { redirect_to experts_url, notice: 'Expert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expert
      @expert = Expert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expert_params
      params.require(:expert).permit(:email, :name, :picture_url)
    end
end

app/helpers/experts_helper.rb
module ExpertsHelper
end

app/views/experts/_form.html.erb
<%= form_with(model: expert, local: true) do |form| %>
  <% if expert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expert.errors.count, "error") %> prohibited this expert from being saved:</h2>

      <ul>
      <% expert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_area :email, id: :expert_email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :expert_name %>
  </div>

  <div class="field">
    <%= form.label :picture_url %>
    <%= form.text_area :picture_url, id: :expert_picture_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/experts/ask_expert.html.erb
<h2><%= @expertise.expert.name + " is knowledgeable about " + @expertise.skill.name %></h2>
<form class="form-aligned">
  <div><%= image_tag @expertise.expert.picture_url %></div>
  <div class="form-group">
    <label class="control-label">My Question Is:</label>
    <%= form_tag({:controller => "experts", :action => "submit_question"}, method: "post", class: "form-control") do %>
    <%= text_area_tag(:question) %>
    <%= submit_tag "Submit Question", class: 'btn btn-success form-inline' %>
  </div>
<% end %>
</form>

app/views/experts/edit.html.erb
<h1>Editing Expert</h1>

<%= render 'form', expert: @expert %>

<%= link_to 'Show', @expert %> |
<%= link_to 'Back', experts_path %>

app/views/experts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Experts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Picture url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experts.each do |expert| %>
      <tr>
        <td><%= expert.email %></td>
        <td><%= expert.name %></td>
        <td><%= expert.picture_url %></td>
        <td><%= link_to 'Show', expert %></td>
        <td><%= link_to 'Edit', edit_expert_path(expert) %></td>
        <td><%= link_to 'Destroy', expert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expert', new_expert_path %>

app/views/experts/look_up_expert.html.erb
<h2>Who are you?</h2>
<form class="form-aligned">
  <div class="form-group">
    <label class="control-label">My Name Is:</label>
    <%= form_tag("/dsfdgsd", method: "get", class: "form-control") do %>
      <%= text_area_tag(:name) %>
      <% end %>
    
      <%= submit_tag "Submit Name", class: 'btn btn-success form-inline' %>
  </div>
</form>

app/views/experts/new.html.erb
<h1>New Expert</h1>

<%= render 'form', expert: @expert %>

<%= link_to 'Back', experts_path %>

app/views/experts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @expert.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @expert.name %>
</p>

<p>
  <strong>Picture url:</strong>
  <%= @expert.picture_url %>
</p>

<%= link_to 'Edit', edit_expert_path(@expert) %> |
<%= link_to 'Back', experts_path %>